### PR TITLE
nashc: Drop `InCallService` and `audio`

### PR DESCRIPTION
**Pull request by M3DZIK**
They have been moved to `hardware/mediatek`.

They generate errors during compilation.

### CODE REVIEW

**Comment by Vlad55432** [comment]
To be honest it needs to be in commit

**Comment by M3DZIK** [comment]
By the way, I would appreciate if you would update hardware_oplus (I'm betting that it is used LineageOS/android_hardware_oplus yes?) and patches.

**Comment by R0rt1z2** [comment]
It would be nice to at least use the common `nashc:` prefix as has been done in all the other commits.

**Comment by R0rt1z2** [comment]
... the commits, not the PR itself.

**Comment by M3DZIK** [comment]
image

When you do a quash and merge, one commit is made and the name pr is the name of the commit

**Comment by M3DZIK** [comment]
> ... the commits, not the PR itself.

image

When you do a quash and merge, one commit is made and the name pr is the name of the commit

**Comment by AntoninoScordino** [comment]
> > ... the commits, not the PR itself.
> 
> image
> 
> When you do a quash and merge, one commit is made and the name pr is the name of the commit

I mean, I understand that you are trying, but it's irrelevant because the developer already knows what he's doing and/or has not modified. He does not only maintain this device, hence why he does not keep up with all the changes made in the different repositories.

**Pull request closed without merging**
